# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zee's Portfolio
email: sayhi@zee.sg
description: >
  Zee is a UI (User Interface) and UX (User Experience) designer based in Singapore
  who crafts friendly and intuitive user interaction and user interface design for the web, mobile devices and apps.
  She codes too, mostly in HTML, CSS and JavaScript.
baseurl: "" # the subpath of your site, e.g. /blog
keywords: ui,ux,digital,app,web,mobile,website,design,designer,development
url: "http://zee.sg" # the base hostname & protocol for your site
twitter_username: GabrielaZee
behance_username: yzixuan
linkedin_username: yzixuan
github_username: yzixuan
# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
